// generated by scripts/_vo/gen.py musashi from scripts/musashi/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "musashi/vo/hook.m4a", dur: 3.08, text: "A thousand new tokens. Everyone is shouting." },
  intro: { file: "musashi/vo/intro.m4a", dur: 3.219, text: "Musashi. Conviction-weighted token intelligence." },
  bnb: { file: "musashi/vo/bnb.m4a", dur: 1.496, text: "Now on BNB Chain." },
  gates: { file: "musashi/vo/gates.m4a", dur: 3.272, text: "Seven gates. Fail one, and it's cut." },
  strike: { file: "musashi/vo/strike.m4a", dur: 4.002, text: "Bull debates bear. Only real conviction is logged on-chain." },
  app: { file: "musashi/vo/app.m4a", dur: 3.298, text: "The real dashboard, reading BSC testnet live." },
  ledger: { file: "musashi/vo/ledger.m4a", dur: 2.569, text: "Its first strike closed up twenty-five percent." },
  aria: { file: "musashi/vo/aria.m4a", dur: 4.08, text: "Live BSC, read-only. ARIA passes five gates." },
  logged: { file: "musashi/vo/logged.m4a", dur: 2.582, text: "Agent zero strikes, with conviction four." },
  proof: { file: "musashi/vo/proof.m4a", dur: 1.915, text: "Deployed on BSC testnet." },
  smoke: { file: "musashi/vo/smoke.m4a", dur: 1.855, text: "Every receipt, status one." },
  stack: { file: "musashi/vo/stack.m4a", dur: 2.664, text: "The Go daemon and the dashboard read the live chain." },
  stats: { file: "musashi/vo/stats.m4a", dur: 3.651, text: "One strike, one win. Zero-G storage skipped." },
  outro: { file: "musashi/vo/outro.m4a", dur: 4.037, text: "Musashi. Find early. Strike with conviction." },
} as const;
export type VoId = keyof typeof VO_LINES;
