// generated by scripts/_vo/gen.py zero-arena from scripts/zero-arena/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "zero-arena/vo/hook.m4a", dur: 3.073, text: "Trading bots post huge returns, and you just have to trust them." },
  intro: { file: "zero-arena/vo/intro.m4a", dur: 3.253, text: "Zero Arena makes AI trading agents prove it, on-chain." },
  bnb: { file: "zero-arena/vo/bnb.m4a", dur: 1.383, text: "Now on BNB Chain." },
  certify: { file: "zero-arena/vo/certify.m4a", dur: 1.809, text: "First, the run hash goes on-chain." },
  mint: { file: "zero-arena/vo/mint.m4a", dur: 2.002, text: "Then the agent is minted as an i-N-F-T." },
  live: { file: "zero-arena/vo/live.m4a", dur: 2.708, text: "An operator commits every live epoch, hash-chained." },
  season: { file: "zero-arena/vo/season.m4a", dur: 2.204, text: "Then a season pays the prize, on-chain." },
  app: { file: "zero-arena/vo/app.m4a", dur: 2.369, text: "The real dashboard, on live testnet data." },
  cert: { file: "zero-arena/vo/cert.m4a", dur: 1.922, text: "The run hash is read straight from the chain." },
  run: { file: "zero-arena/vo/run.m4a", dur: 2.508, text: "The live run: two epochs, chained." },
  settled: { file: "zero-arena/vo/settled.m4a", dur: 1.937, text: "Season one, settled on testnet." },
  chain: { file: "zero-arena/vo/chain.m4a", dur: 1.971, text: "Each epoch is hashed onto the one before." },
  match: { file: "zero-arena/vo/match.m4a", dur: 1.204, text: "Anyone can recompute it." },
  paid: { file: "zero-arena/vo/paid.m4a", dur: 0.986, text: "The winner gets paid." },
  oracle: { file: "zero-arena/vo/oracle.m4a", dur: 1.416, text: "Transfers need a signed proof." },
  proof: { file: "zero-arena/vo/proof.m4a", dur: 1.978, text: "Five contracts, live on testnet." },
  smoke: { file: "zero-arena/vo/smoke.m4a", dur: 2.331, text: "Nine smoke transactions, all status one." },
  stats: { file: "zero-arena/vo/stats.m4a", dur: 1.259, text: "And the hash chain matches." },
  honest: { file: "zero-arena/vo/honest.m4a", dur: 2.351, text: "Honest note: zero G storage was skipped." },
  outro: { file: "zero-arena/vo/outro.m4a", dur: 3.157, text: "Build. Certify. Compete on-chain." },
} as const;
export type VoId = keyof typeof VO_LINES;
