#!/usr/bin/env bash
#
# Cermin-RWA full-stack dev orchestrator (Task 8).
#
# Brings up the whole real-path stack against the local Daml sandbox:
#   1. builds the DAR
#   2. starts `daml start` (Canton sandbox :6865 + HTTP JSON API :7575), running
#      Cermin.Scripts.Demo:demoSetup as the init-script to seed the demo scene
#   3. extracts the allocated party ids + the DAR's package id
#   4. writes agent/.env and backend/.env with MOCK_LEDGER=false
#   5. starts the Guard Agent service and the backend bridge
#   6. prints how to start the frontend pointed at the backend (VITE_API_URL)
#
# Idempotent: re-running kills the previous stack first (scripts/stop.sh) and the
# Canton sandbox is in-memory, so every run starts from a fresh demoSetup scene.
#
# Requires: daml SDK 2.10.4 on PATH, JDK 17, Node. Docker is NOT required (the
# sandbox is the rehearsal env; CN Quickstart LocalNet is the demo-day target —
# see docs/06-demo-runbook.md).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export JAVA_HOME="${JAVA_HOME:-$(brew --prefix openjdk@17 2>/dev/null || echo "")}"
export PATH="${JAVA_HOME:+$JAVA_HOME/bin:}$HOME/.daml/bin:$PATH"

LEDGER_PORT="${LEDGER_PORT:-6865}"
JSON_API_PORT="${JSON_API_PORT:-7575}"
BACKEND_PORT="${BACKEND_PORT:-3001}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"
DAR="$ROOT/daml/.daml/dist/cermin-rwa-0.0.1.dar"
DEV_DIR="$ROOT/.dev"

log()  { printf '\033[36m[dev]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[dev]\033[0m %s\n' "$*"; }
die()  { printf '\033[31m[dev] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

command -v daml >/dev/null 2>&1 || die "daml not on PATH (need SDK 2.10.4; see docs/06-demo-runbook.md)."
command -v node >/dev/null 2>&1 || die "node not on PATH."

mkdir -p "$DEV_DIR"

# 0. Clean slate — idempotent re-run.
log "Stopping any previous stack..."
"$ROOT/scripts/stop.sh" || true

# 1. Build the DAR.
log "Building DAR..."
( cd "$ROOT/daml" && daml build ) >"$DEV_DIR/build.log" 2>&1 || { cat "$DEV_DIR/build.log"; die "daml build failed."; }
[ -f "$DAR" ] || die "DAR not found at $DAR after build."

# 2. Start daml sandbox + JSON API (headless: no Navigator, stdin from /dev/null so
#    the interactive 'r'/Ctrl-C prompt doesn't block the background process).
log "Starting daml sandbox + JSON API (this can take ~60-90s the first time)..."
# `daml start` must run inside the daml project dir (where daml.yaml lives).
nohup bash -c "cd '$ROOT/daml' && exec daml start --start-navigator=no --open-browser=no --sandbox-port '$LEDGER_PORT' --json-api-port '$JSON_API_PORT'" \
  </dev/null >"$DEV_DIR/sandbox.log" 2>&1 &
echo $! >"$DEV_DIR/sandbox.pid"

# 3. Wait for the JSON API to report ready (init-script has already run by then).
log "Waiting for JSON API on :$JSON_API_PORT ..."
for i in $(seq 1 120); do
  if curl -fsS -o /dev/null "http://localhost:$JSON_API_PORT/readyz" 2>/dev/null; then break; fi
  if ! kill -0 "$(cat "$DEV_DIR/sandbox.pid")" 2>/dev/null && ! lsof -ti :"$JSON_API_PORT" >/dev/null 2>&1; then
    tail -30 "$DEV_DIR/sandbox.log" || true
    die "daml start exited before the JSON API came up (see $DEV_DIR/sandbox.log)."
  fi
  sleep 2
  [ "$i" = 120 ] && { tail -30 "$DEV_DIR/sandbox.log"; die "Timed out waiting for JSON API."; }
done
log "JSON API is up."

# 4. Wait for the seeded demo parties, then extract their namespaced ids.
log "Waiting for demoSetup parties..."
PARTIES=""
for i in $(seq 1 30); do
  PARTIES="$(daml ledger list-parties --host localhost --port "$LEDGER_PORT" 2>/dev/null || true)"
  if echo "$PARTIES" | grep -q 'displayName = "Borrower"'; then break; fi
  sleep 2
  [ "$i" = 30 ] && die "demoSetup parties never appeared (see $DEV_DIR/sandbox.log)."
done

party_for() { echo "$PARTIES" | grep "displayName = \"$1\"" | sed -E "s/.*party = '([^']+)'.*/\1/" | head -1; }
PARTY_BORROWER="$(party_for Borrower)"
PARTY_GUARD_AGENT="$(party_for GuardAgent)"
PARTY_ORACLE="$(party_for Oracle)"
[ -n "$PARTY_BORROWER" ] && [ -n "$PARTY_GUARD_AGENT" ] && [ -n "$PARTY_ORACLE" ] \
  || die "Could not extract all demo party ids."

# 5. Extract the DAR's main package id (JSON API v1 needs package-qualified ids).
PACKAGE_ID="$(daml damlc inspect-dar "$DAR" --json 2>/dev/null \
  | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>process.stdout.write(JSON.parse(s).main_package_id))")"
[ -n "$PACKAGE_ID" ] || die "Could not extract main package id from the DAR."

log "Borrower   = $PARTY_BORROWER"
log "GuardAgent = $PARTY_GUARD_AGENT"
log "Oracle     = $PARTY_ORACLE"
log "Package id = $PACKAGE_ID"

# 6. Write agent/.env and backend/.env (real-mode).
cat >"$ROOT/agent/.env" <<EOF
# Generated by scripts/dev.sh — do not commit (gitignored).
LEDGER_URL=http://localhost:$JSON_API_PORT
PARTY_GUARD_AGENT=$PARTY_GUARD_AGENT
LEDGER_PACKAGE_ID=$PACKAGE_ID
POLL_MS=2000
MOCK_LEDGER=false
EOF

cat >"$ROOT/backend/.env" <<EOF
# Generated by scripts/dev.sh — do not commit (gitignored).
PORT=$BACKEND_PORT
LEDGER_URL=http://localhost:$JSON_API_PORT
PARTY_BORROWER=$PARTY_BORROWER
PARTY_ORACLE=$PARTY_ORACLE
LEDGER_PACKAGE_ID=$PACKAGE_ID
MOCK_LEDGER=false
EOF
log "Wrote agent/.env and backend/.env (MOCK_LEDGER=false)."

# 7. Ensure JS deps are installed.
[ -d "$ROOT/agent/node_modules" ]   || ( log "Installing agent deps...";   cd "$ROOT/agent"   && npm install >"$DEV_DIR/agent-install.log" 2>&1 )
[ -d "$ROOT/backend/node_modules" ] || ( log "Installing backend deps..."; cd "$ROOT/backend" && npm install >"$DEV_DIR/backend-install.log" 2>&1 )

# 8. Start the Guard Agent and the backend bridge. Env is passed inline (not only
#    via .env) so the agent's `tsx` start — which does not auto-load .env — still
#    gets its config; the backend reads .env too but inline keeps both uniform.
log "Starting Guard Agent..."
nohup bash -c "cd '$ROOT/agent' && LEDGER_URL='http://localhost:$JSON_API_PORT' PARTY_GUARD_AGENT='$PARTY_GUARD_AGENT' LEDGER_PACKAGE_ID='$PACKAGE_ID' POLL_MS=2000 MOCK_LEDGER=false npm start" \
  </dev/null >"$DEV_DIR/agent.log" 2>&1 &
echo $! >"$DEV_DIR/agent.pid"

log "Starting backend bridge on :$BACKEND_PORT ..."
nohup bash -c "cd '$ROOT/backend' && PORT='$BACKEND_PORT' LEDGER_URL='http://localhost:$JSON_API_PORT' PARTY_BORROWER='$PARTY_BORROWER' PARTY_ORACLE='$PARTY_ORACLE' LEDGER_PACKAGE_ID='$PACKAGE_ID' MOCK_LEDGER=false npm start" \
  </dev/null >"$DEV_DIR/backend.log" 2>&1 &
echo $! >"$DEV_DIR/backend.pid"

# 9. Wait for the backend to answer.
for i in $(seq 1 30); do
  if curl -fsS -o /dev/null "http://localhost:$BACKEND_PORT/api/position" 2>/dev/null; then break; fi
  sleep 1
  [ "$i" = 30 ] && { tail -20 "$DEV_DIR/backend.log"; die "Backend did not come up (see $DEV_DIR/backend.log)."; }
done

log "Stack is up. Logs in $DEV_DIR/{sandbox,agent,backend}.log"
cat <<EOF

  ┌─ Cermin-RWA is running ────────────────────────────────────────────┐
   Ledger gRPC   : localhost:$LEDGER_PORT
   JSON API      : http://localhost:$JSON_API_PORT
   Backend       : http://localhost:$BACKEND_PORT   (GET /api/position)
   Guard Agent   : polling every 2s (tail -f $DEV_DIR/agent.log)

   Start the frontend in backend-polling mode:
     cd frontend && VITE_API_URL=http://localhost:$BACKEND_PORT npm run dev
   then open http://localhost:$FRONTEND_PORT

   Drive the rescue:
     curl -s http://localhost:$BACKEND_PORT/api/sim/price \\
       -H 'Content-Type: application/json' -d '{"price":0.76}' | node -e 0
     # watch the agent fire, then:
     curl -s http://localhost:$BACKEND_PORT/api/position

   Trigger a coupon sweep (issues 112.50 mUSD for the demo borrower):
     cd daml && daml script --dar $DAR \\
       --script-name Cermin.Scripts.Demo:payDemoCoupon \\
       --ledger-host localhost --ledger-port $LEDGER_PORT

   Stop everything:  scripts/stop.sh
  └────────────────────────────────────────────────────────────────────┘
EOF
