// generated by scripts/_vo/gen.py bingo-chain from scripts/bingo-chain/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "bingo-chain/vo/hook.m4a", dur: 2.493, text: "Online bingo? You're trusting the house." },
  house: { file: "bingo-chain/vo/house.m4a", dur: 1.885, text: "Every number is drawn where you can't see it." },
  multi: { file: "bingo-chain/vo/multi.m4a", dur: 2.31, text: "Proven on Celo, now on BNB Chain." },
  celo: { file: "bingo-chain/vo/celo.m4a", dur: 3.626, text: "Nearly five hundred arenas on Celo mainnet, almost nine thousand calls." },
  seal: { file: "bingo-chain/vo/seal.m4a", dur: 2.803, text: "Seal your board. Only its hash goes on-chain." },
  verify: { file: "bingo-chain/vo/verify.m4a", dur: 2.147, text: "The contract replays every call, then pays." },
  app: { file: "bingo-chain/vo/app.m4a", dur: 1.75, text: "The real app, on BSC testnet." },
  split: { file: "bingo-chain/vo/split.m4a", dur: 0.826, text: "They split the pot!" },
  game: { file: "bingo-chain/vo/game.m4a", dur: 2.114, text: "Then a full two-player game, played live." },
  receipts: { file: "bingo-chain/vo/receipts.m4a", dur: 1.152, text: "Thirteen for thirteen." },
  secs: { file: "bingo-chain/vo/secs.m4a", dur: 2.036, text: "Create to settle in thirty-five seconds." },
  fee: { file: "bingo-chain/vo/fee.m4a", dur: 1.352, text: "One percent fee to the treasury." },
  tests: { file: "bingo-chain/vo/tests.m4a", dur: 1.342, text: "Ninety-five tests pass!" },
  outro: { file: "bingo-chain/vo/outro.m4a", dur: 3.507, text: "Bingo Chain. No house. Just the chain." },
} as const;
export type VoId = keyof typeof VO_LINES;
