// generated by scripts/_vo/gen.py liber from scripts/liber/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "liber/vo/hook.m4a", dur: 1.632, text: "You get paid in USDC." },
  qris: { file: "liber/vo/qris.m4a", dur: 2.225, text: "But the caf\u00e9 only takes kris, in rupiah." },
  intro: { file: "liber/vo/intro.m4a", dur: 2.686, text: "Meet Liber: pay kris straight from USDC." },
  bnb: { file: "liber/vo/bnb.m4a", dur: 1.332, text: "Now on BNB Chain." },
  activate: { file: "liber/vo/activate.m4a", dur: 1.315, text: "Your keys stay on your phone." },
  scan: { file: "liber/vo/scan.m4a", dur: 2.26, text: "Scan any kris for a live USDC quote." },
  topup: { file: "liber/vo/topup.m4a", dur: 1.891, text: "One transfer tops up your Kolo card." },
  app: { file: "liber/vo/app.m4a", dur: 2.057, text: "The real app, on BSC testnet." },
  gate: { file: "liber/vo/gate.m4a", dur: 3.186, text: "It activates once the wallet holds point zero zero one BNB." },
  cast: { file: "liber/vo/cast.m4a", dur: 2.975, text: "This top-up was sent with cast, to a stand-in Kolo address." },
  nobnb: { file: "liber/vo/nobnb.m4a", dur: 2.173, text: "No gas yet? Two-oh-two." },
  funded: { file: "liber/vo/funded.m4a", dur: 1.718, text: "Funded? Two-oh-one." },
  balance: { file: "liber/vo/balance.m4a", dur: 2.105, text: "And the balance is read straight from the contract." },
  proof: { file: "liber/vo/proof.m4a", dur: 2.85, text: "Test USDC, live on BSC testnet." },
  smoke: { file: "liber/vo/smoke.m4a", dur: 2.601, text: "The faucet and transfer ran on-chain, via cast." },
  trust: { file: "liber/vo/trust.m4a", dur: 3.135, text: "Zero trustlines. It's just a B-E-P twenty." },
  tests: { file: "liber/vo/tests.m4a", dur: 1.446, text: "Seventy-four tests pass." },
  outro: { file: "liber/vo/outro.m4a", dur: 3.585, text: "Liber. Scan kris, pay from USDC." },
} as const;
export type VoId = keyof typeof VO_LINES;
