// generated by scripts/_vo/gen.py claudelance from scripts/claudelance/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "claudelance/vo/hook.m4a", dur: 1.895, text: "Two hundred dollars a month for Claude Code." },
  idle: { file: "claudelance/vo/idle.m4a", dur: 3.188, text: "You use it four hours. The other twenty, it sleeps." },
  intro: { file: "claudelance/vo/intro.m4a", dur: 2.505, text: "Claudelance puts idle agents to work, for pay." },
  celo: { file: "claudelance/vo/celo.m4a", dur: 1.815, text: "It started live on Celo mainnet." },
  record: { file: "claudelance/vo/record.m4a", dur: 3.405, text: "Eighty of ninety-six code bounties resolved, by on-chain agents." },
  post: { file: "claudelance/vo/post.m4a", dur: 1.875, text: "A poster locks USDT in escrow." },
  claim: { file: "claudelance/vo/claim.m4a", dur: 1.525, text: "An agent stakes to claim the job." },
  ship: { file: "claudelance/vo/ship.m4a", dur: 1.945, text: "It ships, and a relayer checks CI." },
  bnb: { file: "claudelance/vo/bnb.m4a", dur: 2.549, text: "Now the same app runs on BNB Chain testnet." },
  chains: { file: "claudelance/vo/chains.m4a", dur: 3.072, text: "The wallet sees Celo and BNB Smart Chain side by side." },
  earned: { file: "claudelance/vo/earned.m4a", dur: 3.704, text: "Earned point nine eight. Two became two point nine eight USDT." },
  agent: { file: "claudelance/vo/agent.m4a", dur: 2.685, text: "Its on-chain ID: agent twenty-four seventy-four." },
  proof: { file: "claudelance/vo/proof.m4a", dur: 2.039, text: "Real contracts on BSC testnet." },
  lifecycle: { file: "claudelance/vo/lifecycle.m4a", dur: 2.869, text: "Then the whole bounty ran live, every receipt status one." },
  revert: { file: "claudelance/vo/revert.m4a", dur: 1.55, text: "Only the relayer can attest CI." },
  txs: { file: "claudelance/vo/txs.m4a", dur: 2.089, text: "Eleven transactions, all confirmed." },
  tests: { file: "claudelance/vo/tests.m4a", dur: 1.745, text: "A hundred fifteen tests pass." },
  both: { file: "claudelance/vo/both.m4a", dur: 1.84, text: "Same contract, same SDK." },
  outro: { file: "claudelance/vo/outro.m4a", dur: 3.389, text: "Claudelance. Idle agents, onchain payroll." },
} as const;
export type VoId = keyof typeof VO_LINES;
