// generated by scripts/_vo/gen.py neural-alpha from scripts/neural-alpha/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "neural-alpha/vo/hook.m4a", dur: 3.339, text: "Markets never sleep. Bots without guardrails get wrecked." },
  logo: { file: "neural-alpha/vo/logo.m4a", dur: 3.668, text: "Neural Alpha trades BNB Smart Chain, with its risk rules in code." },
  paper: { file: "neural-alpha/vo/paper.m4a", dur: 1.202, text: "All of it in paper mode." },
  ingest: { file: "neural-alpha/vo/ingest.m4a", dur: 3.382, text: "Each cycle: live BSC prices in, nine signals scored." },
  gate: { file: "neural-alpha/vo/gate.m4a", dur: 3.118, text: "A hard risk gate decides. Fills are simulated." },
  real: { file: "neural-alpha/vo/real.m4a", dur: 2.198, text: "The real agent, on live Binance quotes." },
  slots: { file: "neural-alpha/vo/slots.m4a", dur: 1.981, text: "Three slots full, so it stops buying." },
  dash: { file: "neural-alpha/vo/dash.m4a", dur: 5.958, text: "The dashboard shows the same run. With no CMC key, its prices and Fear and Greed are simulated." },
  scan: { file: "neural-alpha/vo/scan.m4a", dur: 2.517, text: "Its scanner reads real mainnet swaps from BSC." },
  match: { file: "neural-alpha/vo/match.m4a", dur: 3.155, text: "Amounts check out. Read only, nothing signed." },
  bad: { file: "neural-alpha/vo/bad.m4a", dur: 1.636, text: "Fifteen addresses pointed at nothing." },
  fixed: { file: "neural-alpha/vo/fixed.m4a", dur: 1.567, text: "Eleven fixed, four removed." },
  narr: { file: "neural-alpha/vo/narr.m4a", dur: 4.281, text: "Narrative-Alpha is a companion strategy tool. It isn't wired into the agent." },
  live: { file: "neural-alpha/vo/live.m4a", dur: 4.714, text: "To go live, it needs a CMC key, a Trust Wallet agent wallet, and USDT." },
  outro: { file: "neural-alpha/vo/outro.m4a", dur: 3.553, text: "Neural Alpha. Risk in code, on BNB Chain." },
} as const;
export type VoId = keyof typeof VO_LINES;
