// generated by scripts/_vo/gen.py drift from scripts/drift/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "drift/vo/hook.m4a", dur: 2.968, text: "Your bot reads the chart. It can't read the macro." },
  intro: { file: "drift/vo/intro.m4a", dur: 2.444, text: "DRIFT is a trading agent that knows the market regime." },
  bnb: { file: "drift/vo/bnb.m4a", dur: 2.126, text: "And its risk guard lives on BNB Chain." },
  regime: { file: "drift/vo/regime.m4a", dur: 3.234, text: "It turns Bitcoin's volatility and trend into a regime, on-chain." },
  veto: { file: "drift/vo/veto.m4a", dur: 3.146, text: "Risk-off blocks longs. Too deep a loss halts the bot." },
  cockpit: { file: "drift/vo/cockpit.m4a", dur: 3.309, text: "The real web cockpit: live markets and out-of-sample research." },
  stub: { file: "drift/vo/stub.m4a", dur: 2.781, text: "The guard is live. The Bybit link is stubbed here." },
  live: { file: "drift/vo/live.m4a", dur: 2.211, text: "On testnet, risk-off vetoes the long." },
  limit: { file: "drift/vo/limit.m4a", dur: 2.162, text: "Past the twenty percent limit, the bot halts." },
  agent: { file: "drift/vo/agent.m4a", dur: 1.284, text: "Only the agent can steer it." },
  forced: { file: "drift/vo/forced.m4a", dur: 1.182, text: "Someone forced risk-on." },
  engine: { file: "drift/vo/engine.m4a", dur: 1.772, text: "The engine put it back, on its own." },
  txs: { file: "drift/vo/txs.m4a", dur: 2.729, text: "Eight live transactions, every receipt status one." },
  gas: { file: "drift/vo/gas.m4a", dur: 3.262, text: "Seven of seven tests, and gas under a ten-thousandth of a test BNB." },
  outro: { file: "drift/vo/outro.m4a", dur: 1.432, text: "The guard has the last word." },
} as const;
export type VoId = keyof typeof VO_LINES;
