"""Turn the captured live runs (scripts/tessera/runs/*) into src/projects/tessera/data.ts, verbatim."""
import json, pathlib
R = pathlib.Path(__file__).parent / "runs"
OUT = pathlib.Path(__file__).parents[2] / "src/projects/tessera/data.ts"

def lines(name):
    out = []
    for l in (R / name).read_text().splitlines():
        if l.strip().startswith("/Users/"):  # zsh `time` footer
            continue
        out.append(l.rstrip())
    while out and not out[-1]: out.pop()
    return out

mcp = json.loads((R / "tessera-mcp-scan.json").read_text())
body = json.loads(mcp["result"]["content"][0]["text"])
bsc = body["chains"][0]
mcp_pretty = json.dumps({"address": body["address"], "chains": [bsc]}, indent=2).splitlines()
# keep the first chain and elide the other 10 (real values, just not all shown)
mcp_pretty = mcp_pretty[:-3] + ["    },", "    … 10 more chains (opBNB 204, …, BSC Testnet 97)", "  ],",
    f'  "totalChainsActive": {body["totalChainsActive"]},', f'  "totalTxCount": {body["totalTxCount"]}', "}"]
tools = [t["name"] for t in json.loads((R / "tessera-tools-list.json").read_text())["result"]["tools"]]
health = lines("tessera-health.txt")
v1 = [l for l in lines("tessera-bscscan-v1.txt") if l.split(":")[0].lower() in ("http/2 301", "location", "server") or l.startswith("HTTP/")]

data = {
    "HOT": lines("tessera-hotwallet.txt"),
    "V3": lines("tessera-pcs-678a.txt"),
    "V2": lines("tessera-pcs-v2.txt"),
    "TESTNET": lines("tessera-pcs-testnet.txt"),
    "HEALTH": health,
    "TOOLS": tools,
    "MCP": mcp_pretty,
    "V1": v1,
}
src = "/** GENERATED by scripts/tessera/gen-data.py from the live runs in scripts/tessera/runs/ (2026-09-26). Verbatim. */\n"
for k, v in data.items():
    src += f"export const {k} = {json.dumps(v, ensure_ascii=False, indent=1)} as const;\n"
OUT.write_text(src)
print(OUT, {k: len(v) for k, v in data.items()})
