// generated by scripts/_vo/gen.py iusd-pay from scripts/iusd-pay/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "iusd-pay/vo/hook.m4a", dur: 2.285, text: "Paying a friend in USDT should be easy." },
  gas: { file: "iusd-pay/vo/gas.m4a", dur: 2.455, text: "But you both need BNB for gas, even to claim." },
  intro: { file: "iusd-pay/vo/intro.m4a", dur: 3.059, text: "Meet i-USD Pay: stablecoin payments and gifts." },
  bnb: { file: "iusd-pay/vo/bnb.m4a", dur: 1.383, text: "Now on BNB Chain." },
  pool: { file: "iusd-pay/vo/pool.m4a", dur: 2.976, text: "Your USDT waits in a pool, sealed to your friend's key." },
  relayer: { file: "iusd-pay/vo/relayer.m4a", dur: 2.424, text: "Then a relayer claims it for them, and pays the gas." },
  app: { file: "iusd-pay/vo/app.m4a", dur: 2.27, text: "The real app, live on BSC testnet." },
  card: { file: "iusd-pay/vo/card.m4a", dur: 2.237, text: "Friends pay your card, not a hex address." },
  send: { file: "iusd-pay/vo/send.m4a", dur: 3.006, text: "Ten USDT to a nickname, with the fee shown up front." },
  auto: { file: "iusd-pay/vo/auto.m4a", dur: 2.889, text: "With auto-claim, it lands in about sixteen seconds." },
  gifts: { file: "iusd-pay/vo/gifts.m4a", dur: 1.035, text: "Or wrap it in a gift." },
  designs: { file: "iusd-pay/vo/designs.m4a", dur: 2.196, text: "Twenty-four designs, registered on-chain." },
  proof: { file: "iusd-pay/vo/proof.m4a", dur: 3.307, text: "Real contracts on BSC testnet, with a test USDT." },
  smoke: { file: "iusd-pay/vo/smoke.m4a", dur: 1.707, text: "And a real payment ran end to end." },
  nogas: { file: "iusd-pay/vo/nogas.m4a", dur: 2.968, text: "The relayer paid the gas. The recipient held none." },
  received: { file: "iusd-pay/vo/received.m4a", dur: 1.79, text: "Nine point nine five received." },
  tests: { file: "iusd-pay/vo/tests.m4a", dur: 3.411, text: "Zero gas held, and eighteen of eighteen contract tests pass." },
  outro: { file: "iusd-pay/vo/outro.m4a", dur: 3.868, text: "i-USD Pay. Send USDT like a text." },
} as const;
export type VoId = keyof typeof VO_LINES;
