// generated by scripts/_vo/gen.py stax from scripts/stax/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "stax/vo/hook.m4a", dur: 2.964, text: "You want Apple and Tesla. You have twenty dollars." },
  risk: { file: "stax/vo/risk.m4a", dur: 3.374, text: "Which ones? How much? And who checks the risk?" },
  intro: { file: "stax/vo/intro.m4a", dur: 3.18, text: "Meet Stax, and Vera, its A.I. investing agent." },
  bnb: { file: "stax/vo/bnb.m4a", dur: 1.383, text: "Now on BNB Chain." },
  say: { file: "stax/vo/say.m4a", dur: 1.462, text: "Tell Vera a goal and an amount." },
  plan: { file: "stax/vo/plan.m4a", dur: 2.528, text: "She picks the mix, and signs it with a risk score." },
  gate: { file: "stax/vo/gate.m4a", dur: 2.748, text: "Too risky? A verifier contract reverts it." },
  swap: { file: "stax/vo/swap.m4a", dur: 1.892, text: "The executor swaps on PancakeSwap." },
  app: { file: "stax/vo/app.m4a", dur: 2.597, text: "This is the real Stax app. One button." },
  picks: { file: "stax/vo/picks.m4a", dur: 2.527, text: "Vera turns the goal into a plan, with reasons." },
  fee: { file: "stax/vo/fee.m4a", dur: 2.102, text: "The fee is up front: a quarter of a percent." },
  vera: { file: "stax/vo/vera.m4a", dur: 4.829, text: "Vera is a registered ERC eighty-oh-four agent. Only her key signs plans." },
  proof: { file: "stax/vo/proof.m4a", dur: 3.749, text: "Real contracts on BSC testnet, with mock Apple and Tesla pools." },
  smoke: { file: "stax/vo/smoke.m4a", dur: 1.341, text: "Then a real twenty-dollar run." },
  blocked: { file: "stax/vo/blocked.m4a", dur: 2.094, text: "And a too-risky plan? Reverted." },
  stats: { file: "stax/vo/stats.m4a", dur: 2.993, text: "Twenty dollars, two stocks, five cents in fees." },
  outro: { file: "stax/vo/outro.m4a", dur: 3.405, text: "Stax. Say it. Vera invests it." },
} as const;
export type VoId = keyof typeof VO_LINES;
