// generated by scripts/_vo/gen.py flowroll from scripts/flowroll/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "flowroll/vo/hook.m4a", dur: 2.905, text: "Every month, payroll cash sits idle, earning nothing." },
  work: { file: "flowroll/vo/work.m4a", dur: 2.015, text: "Flowroll puts that idle payroll to work." },
  bnb: { file: "flowroll/vo/bnb.m4a", dur: 1.9, text: "Now live on BNB Chain testnet." },
  deposit: { file: "flowroll/vo/deposit.m4a", dur: 1.77, text: "The employer funds the cycle up front." },
  earn: { file: "flowroll/vo/earn.m4a", dur: 1.775, text: "An agent parks idle funds in yield." },
  advance: { file: "flowroll/vo/advance.m4a", dur: 2.335, text: "Early pay costs one point five percent, flat." },
  real: { file: "flowroll/vo/real.m4a", dur: 2.373, text: "This is the real app, reading live testnet data." },
  credit: { file: "flowroll/vo/credit.m4a", dur: 3.114, text: "The advance was already repaid. Debt, zero." },
  live: { file: "flowroll/vo/live.m4a", dur: 2.286, text: "Every step here is a real testnet transaction." },
  net: { file: "flowroll/vo/net.m4a", dur: 2.404, text: "A thousand advanced, nine eighty-five received." },
  left: { file: "flowroll/vo/left.m4a", dur: 0.902, text: "Four thousand left." },
  stuck: { file: "flowroll/vo/stuck.m4a", dur: 1.627, text: "Testing caught an old payday bug." },
  fixed: { file: "flowroll/vo/fixed.m4a", dur: 1.385, text: "Now fixed, and tested." },
  proof: { file: "flowroll/vo/proof.m4a", dur: 1.97, text: "Twelve contracts on BSC testnet." },
  mocks: { file: "flowroll/vo/mocks.m4a", dur: 2.196, text: "Mock pools and USDC, for now." },
  fee: { file: "flowroll/vo/fee.m4a", dur: 2.575, text: "A thousand early costs fifteen. That's it." },
  tests: { file: "flowroll/vo/tests.m4a", dur: 1.697, text: "Two sixty-five tests pass!" },
  outro: { file: "flowroll/vo/outro.m4a", dur: 2.808, text: "Flowroll. Payroll that pays for itself." },
} as const;
export type VoId = keyof typeof VO_LINES;
