// generated by scripts/_vo/gen.py golda from scripts/golda/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "golda/vo/hook.m4a", dur: 1.869, text: "All dollars, then the market turns." },
  intro: { file: "golda/vo/intro.m4a", dur: 2.253, text: "Golda is a vault that hedges dollars into gold." },
  bnb: { file: "golda/vo/bnb.m4a", dur: 1.334, text: "Now on BNB Chain." },
  deposit: { file: "golda/vo/deposit.m4a", dur: 2.394, text: "Deposit USDT, get vault shares." },
  decide: { file: "golda/vo/decide.m4a", dur: 2.302, text: "An agent reads the market and sets a gold target." },
  swap: { file: "golda/vo/swap.m4a", dur: 2.719, text: "It swaps via LI.FI, whitelisted calls only." },
  guard: { file: "golda/vo/guard.m4a", dur: 1.769, text: "Gold's priced off a five-minute average." },
  concept: { file: "golda/vo/concept.m4a", dur: 2.052, text: "Concept UI, real testnet numbers." },
  minted: { file: "golda/vo/minted.m4a", dur: 2.094, text: "A thousand in, a thousand shares out." },
  redeem: { file: "golda/vo/redeem.m4a", dur: 2.728, text: "Redeem four hundred. Six hundred stay put." },
  swapped: { file: "golda/vo/swapped.m4a", dur: 4.984, text: "Mainnet fork, not live: a thousand USDT became one point two seven seven wrapped BNB." },
  twap: { file: "golda/vo/twap.m4a", dur: 1.841, text: "Wrapped BNB stands in for gold here." },
  honest: { file: "golda/vo/honest.m4a", dur: 2.606, text: "PAXG has no liquidity on BSC today." },
  bug: { file: "golda/vo/bug.m4a", dur: 2.904, text: "The fork caught a bug: those selectors don't exist on BSC." },
  fixed: { file: "golda/vo/fixed.m4a", dur: 1.282, text: "Twenty-four tests pass." },
  deploy: { file: "golda/vo/deploy.m4a", dur: 3.353, text: "Real testnet deploy: seven transactions, all status one." },
  smoke: { file: "golda/vo/smoke.m4a", dur: 1.673, text: "Then deposit and redeem, live." },
  stats: { file: "golda/vo/stats.m4a", dur: 1.934, text: "Shares track deposits, one to one." },
  blocker: { file: "golda/vo/blocker.m4a", dur: 2.739, text: "Mainnet waits for a liquid PAXG pool on BSC." },
  outro: { file: "golda/vo/outro.m4a", dur: 2.754, text: "Golda. A treasury that hedges itself." },
} as const;
export type VoId = keyof typeof VO_LINES;
