// generated by scripts/_vo/gen.py gridora from scripts/gridora/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "gridora/vo/hook.m4a", dur: 1.634, text: "Grid bots trade your money all night." },
  promise: { file: "gridora/vo/promise.m4a", dur: 2.572, text: "But when a trade goes wrong, what did it actually promise?" },
  intro: { file: "gridora/vo/intro.m4a", dur: 2.596, text: "Gridora is a grid trading agent that keeps receipts." },
  grid: { file: "gridora/vo/grid.m4a", dur: 1.994, text: "Orders ladder inside a volatility band." },
  commit: { file: "gridora/vo/commit.m4a", dur: 1.659, text: "The config hash is locked in first." },
  trade: { file: "gridora/vo/trade.m4a", dur: 1.301, text: "Agent Kit signs locally." },
  attest: { file: "gridora/vo/attest.m4a", dur: 1.21, text: "Then the outcome is sealed." },
  illus: { file: "gridora/vo/illus.m4a", dur: 2.543, text: "An illustration: each buy and sell pair banks the spread." },
  breakout: { file: "gridora/vo/breakout.m4a", dur: 1.514, text: "But if price breaks out of the band..." },
  real: { file: "gridora/vo/real.m4a", dur: 2.641, text: "The real verifier, reading BNB Chain mainnet." },
  tape: { file: "gridora/vo/tape.m4a", dur: 3.172, text: "Thirty-eight real trades, each one checkable on BscScan." },
  testrun: { file: "gridora/vo/testrun.m4a", dur: 2.384, text: "On testnet, it registers and commits its plan." },
  record: { file: "gridora/vo/record.m4a", dur: 2.112, text: "Then it logs a trade, and seals the result." },
  deployed: { file: "gridora/vo/deployed.m4a", dur: 1.937, text: "Three contracts on BSC testnet." },
  status: { file: "gridora/vo/status.m4a", dur: 2.602, text: "Seven transactions. Every one succeeded." },
  mainnet: { file: "gridora/vo/mainnet.m4a", dur: 1.206, text: "Also live on mainnet." },
  stats: { file: "gridora/vo/stats.m4a", dur: 2.171, text: "Thirty-eight trades, twenty-two in the green." },
  honest: { file: "gridora/vo/honest.m4a", dur: 2.616, text: "Live trading needs Agent Kit keys, so it isn't shown." },
  outro: { file: "gridora/vo/outro.m4a", dur: 3.3, text: "Gridora. A trading bot that can't rewrite its history." },
} as const;
export type VoId = keyof typeof VO_LINES;
