// generated by scripts/_vo/gen.py tessera from scripts/tessera/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "tessera/vo/hook.m4a", dur: 3.464, text: "One address, eleven chains, eleven explorers to check by hand." },
  intro: { file: "tessera/vo/intro.m4a", dur: 2.638, text: "Tessera scans them all, and an AI agent can call it." },
  bnb: { file: "tessera/vo/bnb.m4a", dur: 2.875, text: "BNB Chain, op B-N-B and testnet come first." },
  paste: { file: "tessera/vo/paste.m4a", dur: 0.919, text: "Paste any address." },
  fan: { file: "tessera/vo/fan.m4a", dur: 1.749, text: "Eleven RPCs, in parallel." },
  classify: { file: "tessera/vo/classify.m4a", dur: 1.708, text: "Get-code tells a contract from a wallet." },
  report: { file: "tessera/vo/report.m4a", dur: 1.822, text: "A table for you, JSON for agents." },
  hot: { file: "tessera/vo/hot.m4a", dur: 1.706, text: "A real scan of a Binance hot wallet." },
  scroll: { file: "tessera/vo/scroll.m4a", dur: 1.732, text: "Scroll's RPC failed this run." },
  whale: { file: "tessera/vo/whale.m4a", dur: 2.163, text: "A hundred million USDT, read right." },
  router: { file: "tessera/vo/router.m4a", dur: 1.788, text: "Now PancakeSwap's V3 router." },
  flagged: { file: "tessera/vo/flagged.m4a", dur: 2.193, text: "A contract on all three BNB networks." },
  tools: { file: "tessera/vo/tools.m4a", dur: 2.23, text: "The Go backend exposes ten MCP tools." },
  agent: { file: "tessera/vo/agent.m4a", dur: 2.212, text: "Any agent can call scan chain over HTTP." },
  real: { file: "tessera/vo/real.m4a", dur: 2.17, text: "The real web app, BNB Chain first." },
  key: { file: "tessera/vo/key.m4a", dur: 2.63, text: "The agent run needs an API key, so it's not shown." },
  limit: { file: "tessera/vo/limit.m4a", dur: 2.203, text: "Explorer data needs an Etherscan V2 key." },
  readonly: { file: "tessera/vo/readonly.m4a", dur: 2.48, text: "Read only: no contracts, no gas spent." },
  outro: { file: "tessera/vo/outro.m4a", dur: 3.338, text: "Tessera. Evidence over narrative, on BNB Chain." },
} as const;
export type VoId = keyof typeof VO_LINES;
