// generated by scripts/_vo/gen.py bridgeagent from scripts/bridgeagent/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "bridgeagent/vo/hook.m4a", dur: 3.48, text: "Bots flex big gains. No name, no receipts." },
  intro: { file: "bridgeagent/vo/intro.m4a", dur: 2.351, text: "Meet BridgeAgent: an autonomous perps trader." },
  register: { file: "bridgeagent/vo/register.m4a", dur: 2.793, text: "The agent gets an ERC-8004 identity." },
  trade: { file: "bridgeagent/vo/trade.m4a", dur: 2.714, text: "It trades locally, and journals every settled trade." },
  verify: { file: "bridgeagent/vo/verify.m4a", dur: 0.914, text: "Anyone can read it." },
  page: { file: "bridgeagent/vo/page.m4a", dur: 2.752, text: "The real status page, live from BSC testnet." },
  ledger: { file: "bridgeagent/vo/ledger.m4a", dur: 1.514, text: "Two trades, append-only." },
  bps: { file: "bridgeagent/vo/bps.m4a", dur: 1.386, text: "One fifty basis points." },
  smoke: { file: "bridgeagent/vo/smoke.m4a", dur: 2.694, text: "Live: agent one registers, trade one lands." },
  synth: { file: "bridgeagent/vo/synth.m4a", dur: 2.424, text: "Trade two: synthetic, real mirror path." },
  bug: { file: "bridgeagent/vo/bug.m4a", dur: 1.516, text: "BSC blocks broke web3." },
  fix: { file: "bridgeagent/vo/fix.m4a", dur: 0.936, text: "Middleware fixed it." },
  txs: { file: "bridgeagent/vo/txs.m4a", dur: 2.103, text: "Five transactions, all status one." },
  unverif: { file: "bridgeagent/vo/unverif.m4a", dur: 1.809, text: "Not yet verified on BscScan." },
  cast: { file: "bridgeagent/vo/cast.m4a", dur: 1.494, text: "One cast call reads it back." },
  stats: { file: "bridgeagent/vo/stats.m4a", dur: 2.648, text: "Two trades. Thirteen tests pass." },
  honest: { file: "bridgeagent/vo/honest.m4a", dur: 1.693, text: "Hyperliquid trading: not tested." },
  outro: { file: "bridgeagent/vo/outro.m4a", dur: 2.469, text: "BridgeAgent. Receipts included." },
} as const;
export type VoId = keyof typeof VO_LINES;
