// generated by scripts/_vo/gen.py lance-hub from scripts/lance-hub/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "lance-hub/vo/hook.m4a", dur: 1.952, text: "You earn in one app, and play in another." },
  silo: { file: "lance-hub/vo/silo.m4a", dur: 1.499, text: "But each app keeps its own balance." },
  intro: { file: "lance-hub/vo/intro.m4a", dur: 2.192, text: "LanceHub is one shared pool behind both." },
  celo: { file: "lance-hub/vo/celo.m4a", dur: 3.389, text: "On Celo mainnet, fifty-six hundred LANCE, all backed by the pool." },
  deposit: { file: "lance-hub/vo/deposit.m4a", dur: 2.178, text: "Deposit into the pool, and LANCE is minted." },
  redeem: { file: "lance-hub/vo/redeem.m4a", dur: 2.469, text: "Redeem it back any time, for a one percent fee." },
  bingo: { file: "lance-hub/vo/bingo.m4a", dur: 2.874, text: "BingoChain's BSC build lists LANCE as a stake token." },
  proof: { file: "lance-hub/vo/proof.m4a", dur: 4.14, text: "Live on BSC testnet. Each step sent with cast, in test amounts." },
  tests: { file: "lance-hub/vo/tests.m4a", dur: 2.091, text: "Thirteen of thirteen forge tests pass." },
  outro: { file: "lance-hub/vo/outro.m4a", dur: 3.125, text: "LanceHub. One shared pool for the ecosystem." },
  credit: { file: "lance-hub/vo/credit.m4a", dur: 4.75, text: "An internal ecosystem credit, not listed on any exchange. Test amounts only." },
} as const;
export type VoId = keyof typeof VO_LINES;
