// generated by scripts/_vo/gen.py equinox from scripts/equinox/vo.lines (en-GB-RyanNeural) — do not edit
export const VO_LINES = {
  hook: { file: "equinox/vo/hook.m4a", dur: 1.553, text: "BNB crashes while you sleep." },
  intro: { file: "equinox/vo/intro.m4a", dur: 1.294, text: "Meet Equinox Agent." },
  bnb: { file: "equinox/vo/bnb.m4a", dur: 1.37, text: "Now on BNB Chain." },
  deposit: { file: "equinox/vo/deposit.m4a", dur: 1.578, text: "Deposit BNB as collateral." },
  skim: { file: "equinox/vo/skim.m4a", dur: 1.642, text: "The agent borrows USDT." },
  shadow: { file: "equinox/vo/shadow.m4a", dur: 1.55, text: "That cash waits in a shadow wallet." },
  defend: { file: "equinox/vo/defend.m4a", dur: 1.384, text: "Anyone can trigger the defense." },
  mock: { file: "equinox/vo/mock.m4a", dur: 2.795, text: "This is the real frontend, running on mock data for now." },
  dash: { file: "equinox/vo/dash.m4a", dur: 2.751, text: "Collateral, debt and health factor, at a glance." },
  feed: { file: "equinox/vo/feed.m4a", dur: 2.037, text: "Every defense lands in the activity feed." },
  withdraw: { file: "equinox/vo/withdraw.m4a", dur: 1.813, text: "And the shadow wallet is yours to withdraw." },
  live: { file: "equinox/vo/live.m4a", dur: 2.306, text: "Vault one, live on BSC testnet." },
  borrowed: { file: "equinox/vo/borrowed.m4a", dur: 2.649, text: "Fourteen hundred borrowed. Health factor two." },
  back: { file: "equinox/vo/back.m4a", dur: 2.567, text: "Anyone can defend it: back to one point five." },
  venus: { file: "equinox/vo/venus.m4a", dur: 2.829, text: "Venus is tested on a mainnet fork, not deployed yet." },
  deployed: { file: "equinox/vo/deployed.m4a", dur: 2.389, text: "Eight contracts, live on BSC testnet." },
  gas: { file: "equinox/vo/gas.m4a", dur: 2.412, text: "All of it cost under a thousandth of a test BNB." },
  tests: { file: "equinox/vo/tests.m4a", dur: 1.698, text: "All fifteen unit tests pass." },
  outro: { file: "equinox/vo/outro.m4a", dur: 4.236, text: "Equinox Agent. Deposit once, and the agent keeps watch." },
} as const;
export type VoId = keyof typeof VO_LINES;
